### ISSUE TITLE
Strategy for `String` and/or `Bigarray` 

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/stdlib-utf#2]
While the proposal focuses on making a PR for `Bytes` first we should at least think about how we are going to add the functionality to `String` and, possibly, to `Bigarray`. 

In particular we should quickly follow up with a PR for `String` so that programmers do not have to use `Bytes.unsafe_of_string`.

Reusing the names made for `Bytes` should be straightforward. The only question is whether we replicate the `Bytes.utf_x_decode` type and its functions in these modules. 

That is whether we have say for `String`

```ocaml
type utf_decode
val utf_decode_valid : utf_x_decode -> bool
val utf_decode_used_bytes : utf_x_decode -> int
val utf_decode_uchar : utf_x_decode -> Uchar.t
val get_utf_8_uchar : string -> int -> utf_decode
```

or simply: 

```ocaml 
val get_utf_8_uchar : string -> int -> Bytes.utf_decode
```

In fact I think it would be silly for `String.utf_decode` not to be equal to `Bytes.utf_decode` at which point I don't think replicating the funs makes sense. 

We need to check however whether `Bigarray` is allowed (or already has) a dependency on `Bytes`.

**Comment by nojb** [comment]
Is there a chance that different "container" types may need different "decode" types? If not, perhaps the `utf_decode` type (and associated functions) should live in `Uchar`, and the same type could be shared between the different container modules (string, bytes, etc).

**Comment by dbuenzli** [comment]
Aaah that's a nice idea. We could even provide constructors for it. This allows other parts of the eco-system to reuse them.

> Is there a chance that different "container" types may need different "decode" types?

Not that I could think of. If you think about it the decode type is very generic it tells you: 

1. Was the decode valid ? 
2. How many bytes did you read ? 
3. What was the `Uchar.t` ? 

For example it doesn't mention that you are working on an indexed data structure.

**Comment by nojb** [comment]
> We need to check however whether `Bigarray` is allowed (or already has) a dependency on `Bytes`.

I don't think this dependency should be problematic.

What signature do you have in mind for the `Bigarray` variant?

Currently none of the numeric get/set functions are present in `Bigarray` even though the compiler has optimized primitives for them. I believe the issue is that there isn't a natural place for them, given that pretty much every other function in `Bigarray` is fully polymorphic but these functions naturally apply only on the "Bigstring" types (1-dimensional `char` bigarray with C layout). An alternative would be to say that these functions (including the ones proposed in this PR) act on the underlying bytes of *any* type of bigarray.

**Comment by gasche** [comment]
(I was also going to suggest putting the type in `Uchar`.)

**Comment by dbuenzli** [comment]
Thanks @gasche, let's put it in `Uchar`. 

> An alternative would be to say that these functions (including the ones proposed in this PR) act on the underlying bytes of _any_ type of bigarray.

This doesn't work well and is confusing because of indexing unit mismatches. If you are going to have variable length `get`s and `set`s on a buffer, the only reasonable indexing unit to use is the smallest one, i.e. bytes.

I think upstream should bite the bullet and add a `Bigarray.Bytes` module. 

A quick look seems to suggest there's a lot of needless eco-system fragmentation: [bigstringaf](https://github.com/inhabitedtype/bigstringaf), [ocplib-endian](https://github.com/OCamlPro/ocplib-endian), [bigstring_base](https://github.com/janestreet/base_bigstring), [ocaml-bigstring](https://github.com/c-cube/ocaml-bigstring/) (though the latter recommends switching to bigstringaf). I also have two private code bases that exposes these things in yet another manner :-)

Once we have `Bigarray.Bytes`, the signature becomes the same as those for `Bytes` (sadly, the code will have to be duplicated, we are still missing the graal of being able to operate on the contents of both `Bytes` and byte bigarrays uniformly without performance costs).

**Comment by dbuenzli** [comment]
I updated the proposal to put the decodes in `Uchar`. The new interface is [here](https://github.com/dbuenzli/stdlib-utf/blob/master/utf_x.mli). 

With this change I no longer see any strategic problems for `String` and an eventual `Bigarray.Bytes`. So I closed the issue. 

Thanks for the input.
