### ISSUE TITLE
Upstreaming plan

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/stdlib-utf#3]
I have now added tests. In [`test.ml`](https://github.com/dbuenzli/stdlib-utf/blob/master/test.ml) we ensure that all uchars codec according to spec and a few other tidbits. In [`test_long.ml`](https://github.com/dbuenzli/stdlib-utf/blob/master/test_long.ml) I have a longer test (~8min on my machine) that ensures we do not decode invalid byte sequences to any uchar, I don't think people want that in the test suite… 

In any case I think an upstreaming PR sequence could be: 

1. Make a PR for `Bytes` and `Uchar` with the codec. 
2. Make a PR for `String`.
3. Make a PR to make `Buffer` use the `Bytes` encoders.

The day `Bigarray.Bytes` exists I'll happily make a PR to add them there aswell ;-) 

What do you think @gasche @nojb ?

P.S. I'll have to switch to something else in the upcoming days, I hope to be able to get back to it at latest by mid october.

**Comment by nojb** [comment]
Sounds good! Personally I think doing 1. and 2. together would be OK as the implementation for `String` should be a trivial wrapping around that of `Bytes`.

**Comment by dbuenzli** [comment]
> Sounds good! Personally I think doing 1. and 2. together would be OK as the implementation for `String` should be a trivial wrapping around that of `Bytes`.

Yeah I just want to avoid c&p churn in case there is still discussion on names and doc strings. (Working on this already took me much more time than I expected…)

**Comment by dbuenzli** [comment]
In the end did 1. and 2. together which is now merged. 

For reference here are all the PRs:

https://github.com/ocaml/ocaml/pull/10710
https://github.com/ocaml/ocaml/pull/10733
