### ISSUE TITLE
Rename `Uchar.utf_decode_used_bytes` to `Uchar.utf_decode_length` ?

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/stdlib-utf#4]
In JavaScript, strings have an underlying UTF-16 encoding. This means we index UTF-16 code units. 

We could reuse `Uchar.decode` for the result of [this function](https://erratique.ch/software/brr/doc/Jstr/index.html#val-get) which [binds](https://github.com/dbuenzli/brr/blob/466c9bb7611460933fc6001c868b692711dd3d34/src/jstr.ml#L38-L42) to JavaScript's [`codePointAt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt). But it would be more natural to stick the number of used code units (1 or 2) in what is currently called `Uchar.utf_decode_used_bytes`, so that loops get naturally written. 

Maybe we should rename it to `Uchar.utf_decode_length`.

```ocaml 
val utf_decode_length : utf_decode -> int
(** [utf_decode_length d] indicates how many elements in the source where
    consumed by the decode of [d]. This is always strictly positive and 
    smaller or equal to [4]. The magnitude unit depends on the actual 
    decoder; in the decoders of the standard library this is always counted 
    in bytes. *)
```

/cc @nojb

**Comment by dbuenzli** [comment]
Also we use three bits, if we say it's strictly positive we could make the bits represent `1-8`.

**Comment by dbuenzli** [comment]
> Also we use three bits, if we say it's strictly positive we could make the bits represent `1-8`.

Maybe not, lets keep the doc string with 1-4 and let us leave the room to encode `0` if a decoding process would need it (they should not, it's bad for the loops).

It looks unlikely a process would decode from units smaller than bytes and since in all defined UTFs (8, 16, 32) the [most bytes used by characters](http://www.unicode.org/faq/utf_bom.html#gen6) is 4 this should be enough.

**Comment by nojb** [comment]
Sticking to bytes sounds nice & simple.

**Comment by dbuenzli** [comment]
So you are against the renaming ?

**Comment by nojb** [comment]
Sorry, I hadn't read the issue in full detail when I wrote my comment.

Having done so, I think it is OK to rename. To be clear, the only difference is to make it a bit more loop-friendly when binding UTF-16 APIs, right?

**Comment by dbuenzli** [comment]
> Having done so, I think it is OK to rename. To be clear, the only difference is to make it a bit more loop-friendly when binding UTF-16 APIs, right?

Yes, that's the use case. More generally it means we don't assume the elements of the decoded data structure to be necessarily bytes. They can be anything from which we can consume from 1-4 elements.
